import type { Metadata } from "next";
import localFont from "next/font/local";
import HeaderIndex from "@/components/header/index";
import FooterIndex from "@/components/footer/index";
import "./globals.css";
import "./card.js";

import { Open_Sans } from "next/font/google";
import { Lato } from "next/font/google";

const openSans = Open_Sans({
  subsets: ["latin"],
  display: "swap",
});

const lato = Lato({
  subsets: ["latin"],
  display: "swap",
  weight: "400",
});

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={`${geistSans.variable} ${geistMono.variable} ${lato.className} antialiased`}>
        <HeaderIndex />
        {children}
        <FooterIndex />
      </body>
    </html>
  );
}
